### ISSUE TITLE
Make the end to end tests run with Scenarioo docu generation again

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#410]
After switching from grunt to gulp, we did not manage to make the e2e tests run with Scenarioo data generation yet.

Currently, we get the following error. Maybe some change in scenarioo-js is required.

```
scenarioo@scenarioo-vm:~/scenarioo/scenarioo-client$ gulp test-e2e-scenarioo
[20:16:08] Using gulpfile ~/scenarioo/scenarioo-client/gulpfile.js
[20:16:08] Starting 'test-e2e-scenarioo'...
[20:16:08] Finished 'test-e2e-scenarioo' after 3.82 ms
ERROR - failed loading configuration file ./protractor-e2e-scenarioo.conf.js

/home/scenarioo/scenarioo/scenarioo-client/node_modules/gulp-protractor/node_modules/protractor/lib/configParser.js:183
    throw e;
          ^
ReferenceError: jasmine is not defined
    at Object.<anonymous> (/home/scenarioo/scenarioo/scenarioo-client/node_modules/scenarioo-js/lib/scenariooJasmineReporter.js:23:42)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/scenarioo/scenarioo/scenarioo-client/node_modules/scenarioo-js/lib/scenarioo-js.js:21:32)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

/home/scenarioo/scenarioo/scenarioo-client/gulpfile.js:136
            throw e;
                  ^
Error: protractor exited with code 8
```

**Comment by adiherzog** [comment]
This works now, thanks to @xeronimus!
