### ISSUE TITLE
Server can not start up, becasue it tries to create the sketcher directory on server startup.

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#477]
People not upgrading from an existing scenarioo installation, meaning all new sceanrioo users (as I am in my project ;-) ) and not yet having a config.xml in their folder (as I have) will run into following problem:

When starting the server it immediately tries to create some directories (for sketcher app data) in the configured default docu data directory, but the default configured data directory is only valid on our developer machines and will fail, which is a pity, because this means that such users can not start the server (it crashes on start) and can not browse to the config UI for simply change the docu path.

With next release 3.0 this will be solved because of different location of config file and configuration of data directory. 

But for release 2.2 we at least need to have some workaround - easiest way might be to not let it fail, but to retry later again?

The realy annoying thing is:
* If you have a directory configured (might be a missconfiguration also, because you misstyped) the application will not work at all anymore)

I will try to fix this.

**Comment by bruderol** [comment]
Also I still get the same error after putting a config.xml with a proper path configured ... no clue why this still fails ... maybe a permission problem? 

Stack Trace:

Directory not created: /opt/scenarioo/scenarioo-application-data/sketcher
       at org.scenarioo.dao.sketcher.SketcherFiles.createDirectoryIfItDoesNotExist(SketcherFiles.java:179)
       at org.scenarioo.dao.sketcher.SketcherFiles.createRootDirectoryIfNecessary(SketcherFiles.java:59)
       at org.scenarioo.rest.application.ScenariooWebApplication.loadConfiguration(ScenariooWebApplication.java:71)
       at org.scenarioo.rest.application.ScenariooWebApplication.contextInitialized(ScenariooWebApplication.java:49)
       at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4961)
       at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5455)
       at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
       at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
       at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
       at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:634)
       at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1074)
       at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1858)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       at java.lang.Thread.run(Thread.java:745)

**Comment by bruderol** [comment]
Ok, I analysed this further:
1. part of this bug were problems on our VM (probably too less disk space or access rights in the file system, in the path configured, which was a mistake by us). 
2. Behaviour in version 2.1 (I tried it out) in same situation is much better, the error log is more informative and also it does not block the user from going to the Admin UI to configure the documentation path.

Server should handle such situations as follows (as in version 2.1):
1. On startup it does not try to write or create anything as long as there is no save/update request or documentation data to import in the configured path. This is important to give users the chance to startup the application and change the configured path in the config UI.
2. The error message in version 2.1 is more informative telling the user why it was not possible. E.g. in version 2.1 we see following information in stack trace in the server log (when trying to save the configuration):
```
Caused by: javax.xml.bind.MarshalException
 - with linked exception:
[java.io.IOException: No space left on device]
```

I think we should correct this to be the same again as before.

**Comment by bruderol** [comment]
I am working on this, pull request will come soon ...

**Comment by bruderol** [comment]
Bug fixed and merged to release branch. 
I will test RC now ...

**Comment by bruderol** [comment]
Works perfectly ... now it is possible again to start scenarioo, access the config page even with missing or erroneous (wrong path configured) config.xml

**Comment by bruderol** [comment]
@adiherzog please review my commit https://github.com/scenarioo/scenarioo/commit/3a6b49f97f0adf375f9bf73e354b09e4dadd7db6

I cleaned up some code (should be less code now than before) and put some review comments, see also issue #478 and belonging TODO comments in my commit, with some concrete things that I think we should fix/improve.
