### ISSUE TITLE
E2E Tests: Fail on error in console log

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#498]
Let the e2e tests fail, if there are errors in browsers console log.

Implementation details:
* @bruderol knows how to do it, did it for its current project

**Comment by bruderol** [comment]
in progress, I found two tests that output error in browser console:

```
Failures:
1) Create sketch Remember author
  Message:
    Failed: Console errors in browser during test execution detected (1 error):
         [1] http://localhost:9000/components/angular/angular.js 13294:24 [object Object]
    
  Stack:
    Error: Failed: Console errors in browser during test execution detected (1 error):
         [1] http://localhost:9000/components/angular/angular.js 13294:24 [object Object]

        at C:\code\scenarioo\scenarioo-client\prepareProtractor.js:97:21
        at Promise.invokeCallback_ (C:\code\scenarioo\scenarioo-client\node_modules\selenium-webdriver\lib\promise.js:1329:14)
        at TaskQueue.execute_ (C:\code\scenarioo\scenarioo-client\node_modules\selenium-webdriver\lib\promise.js:2790:14)
        at TaskQueue.executeNext_ (C:\code\scenarioo\scenarioo-client\node_modules\selenium-webdriver\lib\promise.js:2773:21)

2) Show step Step does not exist
  Message:
    Failed: Console errors in browser during test execution detected (1 error):
         [1] http://localhost:8080/scenarioo/rest/branch/wikipedia-docu-example/build/last%20successful/usecase/Find%20Page/scenario/find_no_results/pageName/inexistent_page.jsp/pageOccurrence/0/stepInPageOccurrence/42 0:0 Failed to load resource: the server re
sponded with a status of 404 (Not Found)
    
  Stack:
    Error: Failed: Console errors in browser during test execution detected (1 error):
         [1] http://localhost:8080/scenarioo/rest/branch/wikipedia-docu-example/build/last%20successful/usecase/Find%20Page/scenario/find_no_results/pageName/inexistent_page.jsp/pageOccurrence/0/stepInPageOccurrence/42 0:0 Failed to load resource: the server re
sponded with a status of 404 (Not Found)

        at C:\code\scenarioo\scenarioo-client\prepareProtractor.js:97:21
        at Promise.invokeCallback_ (C:\code\scenarioo\scenarioo-client\node_modules\selenium-webdriver\lib\promise.js:1329:14)
        at TaskQueue.execute_ (C:\code\scenarioo\scenarioo-client\node_modules\selenium-webdriver\lib\promise.js:2790:14)
        at TaskQueue.executeNext_ (C:\code\scenarioo\scenarioo-client\node_modules\selenium-webdriver\lib\promise.js:2773:21)

```

**Comment by bruderol** [comment]
there seems to be a third test that fails sometimes.

I pushed the change to a feature branch that can only be integrated when the three console errors are fixed in the e2e tests.

@mi-we @adiherzog @danielsuter would be great if you could integrate this in the minicamp and fix the three console errors in the tests. Thank you.

**Comment by eggerschwiler** [comment]
Integrated develop into this branch to check if we still have errors in the console during e2e tests, unfortunately we do:

Failures:
1) Diff viewer - Choose comparisons hide comparison menu
  Message:
    Failed: Console errors in browser during test execution detected (3 errors):
         [1] http://localhost:8080/scenarioo/rest/branch/Production/build/last%20successful/usecase/FindPageUserInterfaceTest/scenario - Failed to load resource: the server responded with a status of 404 ()
         [2] http://localhost:8080/scenarioo/app.bundle.7ff84d09aa59e3bfe025.js 243:1976 "ERROR" TypeError: Cannot read property 'pagesAndSteps' of null

2) List use cases Display and filter usecases
  Message:
    Failed: Console errors in browser during test execution detected (1 error):
         [1] http://localhost:8080/scenarioo/rest/branch/wikipedia-docu-example/build/2014-03-19/usecase/Donate/scenario/find_donate_page/image/006.png - Failed to load resource: the server responded with a status of 404 ()
    
  Stack:
    Error: Failed: Console errors in browser during test execution detected (1 error):
         [1] http://localhost:8080/scenarioo/rest/branch/wikipedia-docu-example/build/2014-03-19/usecase/Donate/scenario/find_donate_page/image/006.png - Failed to load resource: the server responded with a status of 404 ()
    
        at Spec.jasmine.Spec.addExpectationResult (/home/circleci/repo/scenarioo-client/node_modules/scenarioo-js/lib/reporters/jasmine.js:81:36)
        at /home/circleci/repo/scenarioo-client/prepareProtractor.js:91:21
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

3) Step - Screen Annotations Screen without annotations
  Message:
    Failed: Console errors in browser during test execution detected (4 errors):
         [1] http://localhost:8080/scenarioo/rest/diffViewer/baseBranchName/wikipedia-docu-example/baseBuildName/last%20successful/comparisonName/To%20Projectstart/useCaseName/Donate/scenarioName/find_donate_page/stepIndex/1/stepDiffInfo - Failed to load resource: the server responded with a status of 404 ()

4) Step - View Fallback step exists
  Message:
    Failed: Console errors in browser during test execution detected (4 errors):
         [1] http://localhost:8080/scenarioo/rest/branch/wikipedia-docu-example/build/last%20successful/usecase/Find%20Page/scenario/find_no_results/pageName/inexistent_page.jsp/pageOccurrence/0/stepInPageOccurrence/42?labels=undefined - Failed to load resource: the server responded with a status of 404 ()
         [2] http://localhost:8080/scenarioo/rest/branch/wikipedia-docu-example/build/last%20successful/usecase/Find%20Page/scenario/find_no_results/pageName/inexistent_page.jsp/pageOccurrence/0/stepInPageOccurrence/42?labels=undefined - Failed to load resource: the server responded with a status of 404 ()
         [3] http://localhost:8080/scenarioo/app.bundle.7ff84d09aa59e3bfe025.js 243:1976 "ERROR" TypeError: Cannot read property 'method' of undefined
