### ISSUE TITLE
Improve error log in console on startup

### ISSUE THREAD

**Issue by sibetester** [scenarioo/scenarioo#600]
Using the docker image scenarioo reports and error and stops, but no useful error information is found on the console:

```
INFO  org.scenarioo.rest.application.ScenariooWebApplication: ====================================================
INFO  org.scenarioo.rest.application.ScenariooWebApplication: Scenarioo Viewer is starting up ...
INFO  org.scenarioo.rest.application.ScenariooWebApplication: ====================================================
INFO  org.scenarioo.rest.application.ScenariooWebApplication:   Version: 3.0.0
INFO  org.scenarioo.rest.application.ScenariooWebApplication:   Build date: Thu Dec 01 22:35:42 CET 2016
INFO  org.scenarioo.rest.application.ScenariooWebApplication:   Loading configuration ...
INFO  org.scenarioo.rest.application.ScenariooWebApplication:   configured configuration directory:  /docu
INFO  org.scenarioo.dao.configuration.ConfigurationDaoImpl:   loading configuration from file: /docu/config.xml
INFO  org.scenarioo.rest.application.ScenariooWebApplication:   Configuration loaded.
INFO  org.scenarioo.rest.application.ScenariooWebApplication:   Configured documentation content directory: /docu
INFO  org.scenarioo.rest.application.ScenariooWebApplication:   Updating documentation content directory (will be done asynchronously ...)
INFO  org.scenarioo.business.builds.ScenarioDocuBuildsManager: ********************* update builds ********************************
INFO  org.scenarioo.business.builds.ScenarioDocuBuildsManager: Updating available builds ...
INFO  org.scenarioo.business.builds.ScenarioDocuBuildsManager:   Processing documentation content data in directory: /docu
INFO  org.scenarioo.business.builds.ScenarioDocuBuildsManager: Updating the list of available builds and their states ...
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned @Provider: org.codehaus.jackson.jaxrs.JacksonJsonProvider
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned @Provider: org.codehaus.jackson.jaxrs.JsonParseExceptionMapper
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned @Provider: org.scenarioo.rest.base.exceptions.ExceptionHandler
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned @Provider: org.scenarioo.rest.base.context.ScenarioDocuJAXBContextResolver
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned @Provider: org.codehaus.jackson.jaxrs.JsonMappingExceptionMapper
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned @Provider: org.codehaus.jackson.jaxrs.JacksonJaxbJsonProvider
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned resource: org.scenarioo.rest.configuration.LabelConfigurationsResource
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned resource: org.scenarioo.rest.objectRepository.CustomTabsResource
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned resource: org.scenarioo.rest.sketcher.stepSketch.SketchImageResource
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned resource: org.scenarioo.rest.sketcher.issue.IssueResource
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned resource: org.scenarioo.rest.diffViewer.StepDiffInfoResource
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned resource: org.scenarioo.rest.diffViewer.BuildDiffInfoResource
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned resource: org.scenarioo.rest.sketcher.scenarioSketch.ScenarioSketchResource
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned resource: org.scenarioo.rest.configuration.ConfigurationResource
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned resource: org.scenarioo.rest.diffViewer.ScenarioDiffInfoResource
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned resource: org.scenarioo.rest.builds.BranchBuildsResource
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned resource: org.scenarioo.rest.scenario.ScenariosResource
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned resource: org.scenarioo.rest.step.StepResource
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned resource: org.scenarioo.rest.search.SearchResource
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned resource: org.scenarioo.rest.step.ScreenshotResource
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned resource: org.scenarioo.rest.builds.BuildsImporterResource
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned resource: org.scenarioo.rest.application.VersionResource
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned resource: org.scenarioo.rest.usecase.UseCasesResource
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned resource: org.scenarioo.rest.configuration.BranchAliasesResource
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned resource: org.scenarioo.rest.objectRepository.ObjectStepResource
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned resource: org.scenarioo.rest.objectRepository.GenericObjectsResource
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned resource: org.scenarioo.rest.sketcher.stepSketch.StepSketchResource
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned resource: org.scenarioo.rest.diffViewer.UseCaseDiffInfoResource
INFO  org.jboss.resteasy.plugins.server.servlet.ConfigurationBootstrap: Adding scanned resource: org.scenarioo.rest.diffViewer.StepDiffScreenshotResource
21-Mar-2017 11:18:52.099 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
21-Mar-2017 11:18:52.111 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [/scenarioo] startup failed due to previous errors
INFO  org.scenarioo.rest.application.ScenariooWebApplication: ===================================================
INFO  org.scenarioo.rest.application.ScenariooWebApplication: Scenarioo Viewer stopped.
INFO  org.scenarioo.rest.application.ScenariooWebApplication: ===================================================
```

It would be nice if some cause would be visible in the printed out log directly, such that a user does not have to dig into the docker container logs.

**Comment by sibetester** [comment]
in the tomcat log we found following error info:

```
1-Mar-2017 11:26:26.761 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class org.scenarioo.rest.application.ScenariooWebApplication
 org.scenarioo.api.exception.ResourceNotFoundException: Resource not found: /docu/unknown
	at org.scenarioo.api.util.files.FilesUtil.getListOfFilesFromSubdirs(FilesUtil.java:91)
	at org.scenarioo.api.files.ScenarioDocuFiles.getBuildFiles(ScenarioDocuFiles.java:90)
	at org.scenarioo.api.ScenarioDocuReader.loadBuilds(ScenarioDocuReader.java:71)
	at org.scenarioo.dao.aggregates.ScenarioDocuAggregationDao.loadBuildLinks(ScenarioDocuAggregationDao.java:427)
	at org.scenarioo.business.builds.ScenarioDocuBuildsManager.loadBranchBuildsList(ScenarioDocuBuildsManager.java:214)
	at org.scenarioo.business.builds.ScenarioDocuBuildsManager.updateBuildImportStatesAndAvailableBuildsList(ScenarioDocuBuildsManager.java:187)
	at org.scenarioo.business.builds.ScenarioDocuBuildsManager.updateAllBuildsAndSubmitNewBuildsForImport(ScenarioDocuBuildsManager.java:177)
	at org.scenarioo.business.builds.ScenarioDocuBuildsManager.updateBuildsIfValidDirectoryConfigured(ScenarioDocuBuildsManager.java:170)
	at org.scenarioo.rest.application.ScenariooWebApplication.contextInitialized(ScenariooWebApplication.java:54)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1107)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1841)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

seems to be a problem with the data directory.

I am further investigating with help of @bruderol

**Comment by sibetester** [comment]
After investigation we found the root cause:

Branch directory with name "Archive" was containing a branch.xml with name `unknown` which is considered an invalid branch directory. Somehow scenarioo tries to read from wrong directory, instead of reporting inconsistent branch and ignoring it. the wrong name was because we copied an old branch without changing the name in the branch.xml. expected behaviour: the error should give some better information what went wrong and this should not stop the server from starting up but just ignore the invalid branch directory with a warning in the log.

**Comment by bruderol** [comment]
important that we address that - the error output is really unuseful if there is some inconsistency in data.

**Comment by bruderol** [comment]
Another issue that occured recently, that was very similar: The server reported that he wanted to access a build from a Diff (diff-viewer directory) - but that build was not there anymore and this let the server as well crash on startup - such things should not block the server from starting.

**Comment by bruderol** [comment]
@simonberner I could reproduce the problems - currently working on mitigating them. In next release this will be improved. Coming soon ...

**Comment by bruderol** [comment]
What I improved:
* fix for corrupt branch directories: when name in branch.xml is wrong, the branch is just ignored with according output, and startup continues
* for corrupt build files the behaviour is allready ok, nothing to do here.
