### ISSUE TITLE
Dont let startup or build updates fail because of corrupt branch or build files that can't be read.

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#702]
How to reproduce:
if in a branch or build directory the branch.xml or build.xml is somehow corrupt the server crashes on startup or duriong update of all builds.

Expected behaviour:
the corrupted branch or build directory should be ignored and an error should be logged in the log, but the server should still startup and ignore the corrupted data.

**Comment by bruderol** [comment]
reported by @adiherzog on PR https://github.com/scenarioo/scenarioo/pull/693

Stacktrace:
````
INFO  ScenarioDocuBuildsManager     :   Processing documentation content data in directory: /var/lib/scenarioo/data/develop
INFO  ScenarioDocuBuildsManager     : Updating the list of available builds and their states ...
ERROR ScenariooWebApplication       : ====================================================
ERROR ScenariooWebApplication       : Error during Scenarioo startup
java.lang.RuntimeException: Could not unmarshall /var/lib/scenarioo/data/develop/scenarioo-feature-692-create-comparison-dialogue/branch.xml
        at org.scenarioo.api.util.xml.ScenarioDocuXMLFileUtil.unmarshal(ScenarioDocuXMLFileUtil.java:69)
        at org.scenarioo.api.util.xml.ScenarioDocuXMLFileUtil.unmarshalListOfFiles(ScenarioDocuXMLFileUtil.java:84)
        at org.scenarioo.api.ScenarioDocuReader.loadBranches(ScenarioDocuReader.java:57)
        at org.scenarioo.business.builds.ScenarioDocuBuildsManager.loadBranchBuildsList(ScenarioDocuBuildsManager.java:204)
```

**Comment by bruderol** [comment]
Easiest way to fix this would need to release a new version of the writer and reader library.

**Comment by bruderol** [comment]
See scenarioo/scenarioo-java#14
