### ISSUE TITLE
Run unit test in headless Chrome instead of PhantomJS

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#707]
Since upgrading to node 8.11.2 our unit tests fail every now and then on the CI. 

Error message:

```
16:24:06 28 05 2018 16:24:03.652:WARN [PhantomJS 2.1.1 (Linux 0.0.0)]: Disconnected (2 times), because no message in 60000 ms.
16:24:06 PhantomJS 2.1.1 (Linux 0.0.0) ERROR
16:24:06   Disconnected, because no message in 60000 ms.
16:24:06 
16:24:06 
16:24:06 npm ERR! Test failed.  See above for more details.
16:24:06 
16:24:06 > Task :scenarioo-client:npm_test FAILED
16:24:06 :scenarioo-client:npm_test (Thread[main,5,main]) completed. Took 2 mins 18.767 secs.
16:24:06 
16:24:06 FAILURE: Build failed with an exception.
16:24:06 
16:24:06 * What went wrong:
16:24:06 Execution failed for task ':scenarioo-client:npm_test'.
16:24:06 > Process 'command '/var/lib/jenkins/jobs/scenarioo/branches/develop/workspace/scenarioo-client/.gradle/nodejs/node-v8.11.2-linux-x64/bin/node'' finished with non-zero exit value 1
16:24:06 
16:24:06 * Try:
16:24:06 Run with --debug option to get more log output. Run with --scan to get full insights.
16:24:06 
16:24:06 * Exception is:
16:24:06 org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':scenarioo-client:npm_test'.
16:24:06 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
16:24:06 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
...
16:24:06 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
16:24:06 Caused by: org.gradle.process.internal.ExecException: Process 'command '/var/lib/jenkins/jobs/scenarioo/branches/develop/workspace/scenarioo-client/.gradle/nodejs/node-v8.11.2-linux-x64/bin/node'' finished with non-zero exit value 1
16:24:06 	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:389)
16:24:06 	at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:36)
...
org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
16:24:06 	... 95 more
16:24:06 
```

Suggested solution: switch to using headless Chrome for unit tests, as PhantomJS is not supported anymore anyway.

**Comment by bruderol** [comment]
I close since that seems to be merged - right ??
