### ISSUE TITLE
Branch / build still shown in menu while reimport is in state PROCESSING

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#725]
# Impact

Small, it's mainly a cosmetic issue and might be confusing the user while the import is running.

# Steps

* Build is imported (import status "SUCCESS")
* Trigger reimport of build
* Reload Scenarioo viewer (with disabled caching in the dev tools)
* Build has import status "PROCESSING" but is visible in branch / build selection menu. When the build is selected, no use cases are shown and the call to http://localhost:8080/scenarioo/rest/diffViewer/baseBranchName/August-Release/baseBuildName/last%20successful/buildDiffInfos fails with status 500

Exception in log:

```
ERROR RuntimeExceptionHandler       : Runtime exception
java.lang.IllegalArgumentException: Not possible to access this build org.scenarioo.rest.base.BuildIdentifier@13406468[A
ugust-Release,last successful]. It is unavailable, or not yet imported or updated successfully.
        at org.scenarioo.business.builds.ScenarioDocuBuildsManager.validateBuildIsSuccessfullyImported(ScenarioDocuBuild
sManager.java:260)
        at org.scenarioo.business.builds.ScenarioDocuBuildsManager.resolveBuildAlias(ScenarioDocuBuildsManager.java:141)

        at org.scenarioo.business.builds.ScenarioDocuBuildsManager.resolveBranchAndBuildAliases(ScenarioDocuBuildsManage
r.java:123)
        at org.scenarioo.rest.diffViewer.BuildDiffInfoResource.getBuildDiffInfos(BuildDiffInfoResource.java:61)
```

![image](https://user-images.githubusercontent.com/3780183/41653382-296390b2-7486-11e8-93c4-b794daa47224.png)

**Comment by bruderol** [comment]
I think we are starting to improve minor things now, that are not important - please move to next release - probably this is not new.

**Comment by bruderol** [comment]
The build is not visible cause it does not exist while being imported. So that is why no build is selected. The branch still exists.

@adiherzog What would be your proposal to improve this??

**Comment by bruderol** [comment]
@adiherzog I removed the “bug” label. While I agree this is not optimal, I think it is no bug. Read about “Zero Bugs” if you not agree ;-)
See https://medium.com/qualityfaster/the-zero-bug-policy-b0bd987be684
