### ISSUE TITLE
DiffViewer: NullPointerException in ScreenshotComparator

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#750]
### Impact

Some comparisons fail. But it does not happen for all comparisons. So it seems to be related to certain data constellations or even system instability.

### Description

I just tried out the new version 4.0.0 in our project and ran into a NullPointerException in the ScreenshotComparator

```
Scenario develop/MyBuild/MyUseCase/MyScenario has addedElements: 0 changedElements: 11 removedElements: 0 changeRate: 9.070944388510666
FAILURE on comparing build develop/MyBuild with defined comparison: Develop July 11 to Master June 14
           see following exception messages and stack trace: 
             > java.lang.NullPointerException
             > 	at javax.imageio.ImageIO.write(ImageIO.java:1538)
             > 	at org.scenarioo.business.diffViewer.comparator.ScreenshotComparator.compareScreenshots(ScreenshotComparator.java:133)
             > 	at org.scenarioo.business.diffViewer.comparator.ScreenshotComparator.compare(ScreenshotComparator.java:72)
             > 	at org.scenarioo.business.diffViewer.comparator.StepComparator.compareElementAndWrite(StepComparator.java:83)
             > 	at org.scenarioo.business.diffViewer.comparator.StepComparator.compareElementAndWrite(StepComparator.java:35)
             > 	at org.scenarioo.business.diffViewer.comparator.AbstractStructureComparator.compareElementsAndWrite(AbstractStructureComparator.java:82)
             > 	at org.scenarioo.business.diffViewer.comparator.AbstractStructureComparator.calculateDiffInfo(AbstractStructureComparator.java:69)
             > 	at org.scenarioo.business.diffViewer.comparator.StepComparator.compare(StepComparator.java:66)
             > 	at org.scenarioo.business.diffViewer.comparator.ScenarioComparator.compareElementAndWrite(ScenarioComparator.java:72)
             > 	at org.scenarioo.business.diffViewer.comparator.ScenarioComparator.compareElementAndWrite(ScenarioComparator.java:34)
             > 	at org.scenarioo.business.diffViewer.comparator.AbstractStructureComparator.compareElementsAndWrite(AbstractStructureComparator.java:82)
             > 	at org.scenarioo.business.diffViewer.comparator.AbstractStructureComparator.calculateDiffInfo(AbstractStructureComparator.java:69)
             > 	at org.scenarioo.business.diffViewer.comparator.ScenarioComparator.compare(ScenarioComparator.java:58)
             > 	at org.scenarioo.business.diffViewer.comparator.UseCaseComparator.compareElementAndWrite(UseCaseComparator.java:62)
             > 	at org.scenarioo.business.diffViewer.comparator.UseCaseComparator.compareElementAndWrite(UseCaseComparator.java:29)
             > 	at org.scenarioo.business.diffViewer.comparator.AbstractStructureComparator.compareElementsAndWrite(AbstractStructureComparator.java:82)
             > 	at org.scenarioo.business.diffViewer.comparator.AbstractStructureComparator.calculateDiffInfo(AbstractStructureComparator.java:69)
             > 	at org.scenarioo.business.diffViewer.comparator.UseCaseComparator.compare(UseCaseComparator.java:48)
             > 	at org.scenarioo.business.diffViewer.ComparisonExecutor.calculateComparison(ComparisonExecutor.java:182)
             > 	at org.scenarioo.business.diffViewer.ComparisonExecutor.lambda$scheduleComparison$0(ComparisonExecutor.java:130)
             > 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
             > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
             > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
             > 	at java.lang.Thread.run(Thread.java:745)
=== END OF BUILD COMPARISON (failed) ===
```

The line that has the exception (ScreenshotComparator.java:133):

```
ImageIO.write(diffImage, "PNG", diffScreenshot);
```
The actual exception is then in ImageIO.java:1538

Seems this happens when the folder for the diffScreenshot does not exist:

https://stackoverflow.com/a/11154485/581553

So we have to verify this path exists before calling the write function.

It looks like we already create the folder. But we don't assert that it actually exists.

```
if (diffScreenshot.getParentFile() != null) {
    diffScreenshot.getParentFile().mkdirs();
}
```

The error message should be improved to give more info about which Use Case / Scenario / Step was being compared when the error happened.

**Comment by adiherzog** [comment]
After re-running the same comparison again, the error did not happen again. I'll close it and will reopen it in case the same issue happens again.
